version: 2
updates:
  - package-ecosystem: npm
    directories:
      - '/'
    schedule:
      interval: weekly
      day: monday
      time: '12:00'
      timezone: Asia/Bangkok
    cooldown:
      default-days: 7
    open-pull-requests-limit: 1
    groups:
      all:
        patterns:
          - '*'
    allow:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-minor'
          - 'version-update:semver-patch'
    commit-message:
      prefix: 'chore(deps)'

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
    open-pull-requests-limit: 1
    groups:
      all:
        patterns:
          - '*'
    commit-message:
      prefix: 'chore(deps)'
