on:
  push:
    branches: [master]

# See https://docs.npmjs.com/trusted-publishers
permissions:
  id-token: write
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          # Use "rebasecop" credential to push to `master` branch
          # which the branch is protected by https://github.com/taskworld/positioning-strategy/settings/branch_protection_rules/25790813
          token: ${{ secrets.GIT_PUSH_TOKEN }}

      - uses: actions/setup-node@v6
        with:
          node-version-file: 'package.json'
          registry-url: 'https://registry.npmjs.org'

      - uses: pnpm/action-setup@v6

      - run: pnpm install --ignore-scripts

      - run: pnpm exec make-next-release
        env:
          # Use "rebasecop" credential to create a new release
          # at https://github.com/taskworld/positioning-strategy/releases
          GITHUB_TOKEN: ${{ secrets.GIT_PUSH_TOKEN }}
