on:
  push:
    branches: [master]

permissions:
  id-token: write # See https://docs.npmjs.com/trusted-publishers
  contents: write # Allow pushing a new tag and creating a new release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v6
        with:
          node-version-file: 'package.json'
          registry-url: 'https://registry.npmjs.org'

      - uses: pnpm/action-setup@v5

      - run: pnpm install --ignore-scripts

      - run: pnpm exec make-next-release
        env:
          # Use the service account credential to bypass branch protection rules
          # See https://github.com/taskworld/positioning-strategy/settings/branch_protection_rules/25790813
          GITHUB_TOKEN: ${{ secrets.GIT_PUSH_TOKEN }}
